### ISSUE TITLE
Compatibility with babel-preset-es2015

### ISSUE THREAD

**Issue by teohhanhui** [systemjs/plugin-babel#10]
```js
System.config({
  babelOptions: {
    "presets": [
        "babel-preset-es2015"
    ]
  }
});
```
causes `require is not a function`

**Comment by guybedford** [comment]
Presets in the plugin reference modules to load the presets from with SystemJS (`System.import('babel-preset-es2015')`). By default the plugin comes with the es2015 preset, you don't need to provide it at all.

**Comment by teohhanhui** [comment]
Yes, I'm aware that it comes by default with es2015 and stage3 but that's not the issue here.

Trying to load those presets shouldn't cause the whole thing to break. (At least put a visible warning somewhere if that can't be fixed?)
