### ISSUE TITLE
babelOptions.sourceMaps or sourceMap?

### ISSUE THREAD

**Issue by frankwallis** [systemjs/plugin-babel#13]
https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L49 uses ```sourceMaps```:

```
var defaultBabelOptions = {
  modularRuntime: true,
  sourceMaps: true,
  es2015: true,
  stage3: true,
  moduleName: false
};
```
but https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L140 uses ```sourceMap```:
```
    var output = babel.transform(load.source, {
      plugins: plugins,
      presets: presets,
      filename: load.address,
      sourceMap: babelOptions.sourceMap,
      inputSourceMap: load.metadata.sourceMap,
```

**Comment by guybedford** [comment]
Thanks, System sourceMaps were broken in Babel until the commit last night so there was no pressure on this. Working on it now.
