### ISSUE TITLE
What is the purpose of this plugin?

### ISSUE THREAD

**Issue by rchedrese-va** [systemjs/plugin-babel#15]
I'm having a really hard time understanding what the difference is between using this plugin and just using babel directly. What's the difference between `transpiler: 'babel'` and `transpiler: 'plugin-babel'` Could you please clarify?

**Comment by guybedford** [comment]
This plugin provides Babel 6 support, while `transpiler: 'babel'` is the internal transpilation layer in SystemJS itself which is being deprecated in the next major and only supports Babel 5.
