### ISSUE TITLE
Disable es2015 while still being able to build

### ISSUE THREAD

**Issue by dariocravero** [systemjs/plugin-babel#16]
Hi all,

I'm trying to figure out how to disable es2015 transpiling and still get a single file build through rollup in `jspm@beta`. While looking at its source, `plugin-babel` comes with [es2015: true](https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L50) by default which I can override in.

I made a [fork](https://github.com/UXtemple/jspm-react-component-demo/tree/es2015-false) of jspm-react-component-demo [that sets `"es2015": false` in `"babelOptions"](https://github.com/UXtemple/jspm-react-component-demo/blob/es2015-false/jspm.config.js#L36) and it stops the transpiling of es2015 features as expected but it doesn't bundle everything into one file as rollup would do, here's the output:

```
jspm-react-component-demo [es2015-false*] $ jspm build jspm-react-component - react dist/jspm-react-component.js   --format umd --global-name jspmReactComponent --global-deps "{'react':'React'}" --skip-source-maps
     Creating the single-file build for jspm-react-component - react...

       ── jspm-react-component/component.js

ok   Fully-optimized - entire tree built via Rollup static optimization.

ok   Built into dist/jspm-react-component.js, unminified as umd.
```

[This conditional](https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L113-L116) seems to be dealing with it but for some reason it's not outputting the full bundle.

I don't know if this should make any difference at all but I've also tried including [`babel-plugin-transform-es2015-modules-systemjs` like you do when `es2015: true`](https://github.com/systemjs/plugin-babel/blob/master/build-babel/systemjs-babel.js#L4) but I [get the same result](https://github.com/UXtemple/jspm-react-component-demo/blob/es2015-false--babel-plugin-transform-es2015-modules-systemjs/dist/jspm-react-component.js).

Would you have any hints on how to fix this if it's an issue or what am I missing if I'm doing the wrong thing? :)
Thanks!
Darío

**Comment by guybedford** [comment]
Thanks, added in https://github.com/systemjs/plugin-babel/commit/307aba3dabcc6b042234fc476023e7a2a892a139. The release should be out in the next day or so.

**Comment by dariocravero** [comment]
Thanks for the quick reply :). I tried that patch and it didn't make a difference to me though :(. Would there be anything else happening around `es2015: true` that would affect this?

**Comment by guybedford** [comment]
Thanks for letting me know. I got the conditional backwards! It should work now.

**Comment by dariocravero** [comment]
Great! That works, thanks. Now, time to understand the bundled output :)

**Comment by dariocravero** [comment]
So, just to clarify this: the idea is that in the builder you don't want babel to convert exports, right?

**Comment by guybedford** [comment]
Yes exactly.
