### ISSUE TITLE
SyntaxError with v0.0.3

### ISSUE THREAD

**Issue by dbrelovsky** [systemjs/plugin-babel#17]
I get the following exception with plugin-babel@0.0.3:

`Uncaught (in promise) SyntaxError: http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/babel-helpers/slicedToArray.js: Unexpected token (37:2)`

Seems like there are some parenthesis missing for the IIFE to work?

**Comment by guybedford** [comment]
Thanks, I've pushed out a 0.0.4 with a fix. Let me know if that works for you.

**Comment by dbrelovsky** [comment]
Wow - this was fast! Its working now - thank you
