### ISSUE TITLE
Support for module transforms only.

### ISSUE THREAD

**Issue by backspaces** [systemjs/plugin-babel#19]
With Canary at 96% es6 complete, I'd like to use es6-module-loader with babel only transpiling the module import/export statements.  I believe this will be needed as we get closer to all browsers being nearly es6 complete, but still needing module loading.

To be clear, my goal is to use the `<script type='module'>` tag which is likely to be the first native browser module loading. Thus my use of es6-module-loader, currently with traceur which unfortunately transpiles everything.

Let me know if there is another way to achieve this!

**Comment by tyscorp** [comment]
No way! My goal is to use the, too!

**Comment by jryans** [comment]
You should be able to achieve this by disabling the default babel presets with:

```js
  babelOptions: {
    "es2015": false,
    "stage3": false
  }
```

in your `jspm.config.js`.

**Comment by backspaces** [comment]
I'm not using jspm, but es6-module-loader. But I'd also need to add module transpilation to the babelOptions .. not sure how to do that in the browser .. which babel has abandoned, alas.

**Comment by guybedford** [comment]
Note the es6-module-loader project on its own does not come with production workflows without using custom hooks on top of it.
