### ISSUE TITLE
Unable to hit breakpoint

### ISSUE THREAD

**Issue by Alphapage** [systemjs/plugin-babel#25]
Hello,

I have difficulties to debug my code using plugin-babel.
If i put a breakpoint in my es6 file test.js, the breakpoint is never hit by chrome dev. I must insert ```debugger``` line and the debugger breaks in test.js!transpiled.
If I put a breakpoint in test.js!transpiled, the breakpoint doesn't work.

Could you tell me how do you debug the es6 code ? I don't see any sourcemap.
Maybe changing extension in test.js!transpiled to test.js!transpiled.js could solve the breakpoint problem.

Thank you in advance for your help.

**Comment by Alphapage** [comment]
I added sourcemap option to babel and now, the debugger line is hit in my es6 file, but the breakpoints are never applied: only `debugger` is working. Any idea ?

**Comment by guybedford** [comment]
Perhaps try the fix in https://github.com/systemjs/systemjs/pull/1180 here, which may have been causing this.
