### ISSUE TITLE
nodejs harmony

### ISSUE THREAD

**Issue by Alphapage** [systemjs/plugin-babel#27]
Hello,

The issue is related to https://github.com/systemjs/systemjs/issues/1173.

I think systemjs or the plugin doesn't care about the nodejs environment, so it tries to require('path') from current folder.
Any idea ?

**Comment by guybedford** [comment]
We build babel plugins with jspm here for inclusion. See how this is done in the `build-babel` folder here. I'm tracking a modern browser build in https://github.com/systemjs/plugin-babel/issues/28 skipping supported ES6 features.
