### ISSUE TITLE
Update Babel

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-babel#34]
Node 6 support should be coming with the next update

**Comment by perrin4869** [comment]
Seems to be fixed now, Node 6 builds and passes tests: https://travis-ci.org/babel/babel/builds/130473389

**Comment by alexisvincent** [comment]
Status?

**Comment by DavidStrada** [comment]
I had to downgrade to version v5.11.1 on node v6 the problem persist. In other words still broken, waiting to give it a try on next release/update.

**Comment by guybedford** [comment]
We are running the latest Babel here which has Node 6 support.
