### ISSUE TITLE
ES module plugin?

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-babel#37]
We may need to add the code:

```javascript
pluginAndPresetModules = pluginAndPresetModules.map(function(m) {
  return m.default || m;
});
```

To https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L102 in order to support ES module plugins.

**Comment by Vanuan** [comment]
Ok, I'll try

**Comment by Vanuan** [comment]
Strange

     err  Error: ENOENT: no such file or directory, open '-id'
       at Error (native)
    Error loading -id

**Comment by Vanuan** [comment]
Looks to be working.

**Comment by guybedford** [comment]
Thanks for confirming - I've merged a slight adjustment to this in https://github.com/systemjs/plugin-babel/commit/a4110ccf4e064a8d18943d653ed1a0d5f547c77b.
