### ISSUE TITLE
Support for Bluebird coroutines

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-babel#4]
If users want to use Bluebird promises for performance, we should provide an easy option to use this transformer without having to do more than setting the option and installing bluebird.

**Comment by kirly-af** [comment]
Anything new concerning this issue ?

**Comment by guybedford** [comment]
I'm not sure if output to Bluebird coroutines is still provided in Babel 6 actually? Do you know? If it is, we can certainly add an option here.

Otherwise it may be worth trying to install a third-party Babel plugin to try this out.

**Comment by guybedford** [comment]
Ok it is still supported via the plugin at http://babeljs.io/docs/plugins/transform-async-to-module-method/.

It would be possible to integrate this manually by installing it and configuring the plugin, but we could integrate this as an option as well potentially.

**Comment by kirly-af** [comment]
Here is what I did:

```
jspm install npm:babel-plugin-transform-async-to-module-method
jspm install npm:bluebird
```

And below is a part of `jspm.config.js` file:
``` javascript
SystemJS.config({
  transpiler: "plugin-babel",
  packages: {
    "mypackage": {
      "format": "esm",
      "main": "main.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              ["transform-async-to-module-method", {
                "module": "bluebird",
                "method": "coroutine"
              }]
            ]
          }
        }
      }
    }
  }
});
```

However, Bluebird library does not seem to be loaded
``` js
typeof Promise.setScheduler // undefined
```

Is it because plugin-babel does not support `.babelrc` syntax ? If yes, would be great that it is specified in the README. In the same way, adding a line in the README explaining if the plugin considers `.babelrc` files.

Though, being able to set this behavior by passing a simple option sounds good to me. I guess most Angular < 2 developers who start working with ES6+ will need to use Bluebird coroutines to work with `async`/`await`.

**Comment by guybedford** [comment]
Are you sure the configuration is applying? Because the plugin name should be `babel-plugin-transform-async-to-module-method` I think?

**Comment by kirly-af** [comment]
Well, from the plugin documentation that you can find [here](http://babeljs.io/docs/plugins/transform-async-to-module-method/) or [here](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-async-to-module-method), the usage in .babelrc is the following:

``` js
// without options
{
  "plugins": ["transform-async-to-module-method"]
}

// with options
{
  "plugins": [
    ["transform-async-to-module-method", {
      "module": "bluebird",
      "method": "coroutine"
    }]
  ]
}
```

I tried to replace it with `babel-plugin-transform-async-to-module-method` and it did not help (same output). I am a bit confused actually. What name should I used ? The one of babel docs, the package name, or the name specified in the `map` section of the `jspm.config.js` file ?

This is not clearly explained in JSPM docs:

[plugin-babel README](https://github.com/systemjs/plugin-babel#custom-presets-and-transforms):
``` js
babelOptions: {
  plugins: [
    [ "react-transform", {
      "transforms": [{"transform": "react-transform-jspm-hmr"}]
    }]
  ]
}
```

[jspm beta docs](http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html):
``` js
"babelOptions": {
  "plugins": ["babel-plugin-transform-react-jsx"]
}
```

Btw, would it help if I provide my full `jspm.config.js` ?

**Comment by guybedford** [comment]
I've updated the options example at https://github.com/systemjs/plugin-babel#custom-presets-and-transforms to show using bluebird coroutines.

In terms of loading bluebird, it's probably best to have a script tag in the head, but you could also import it via System.import. Then to use the same version of bluebird in SystemJS you could try something like `System.set('bluebird', System.newModule({ default: window.bluebird }))`.
