### ISSUE TITLE
Run in Stage 1 Mode

### ISSUE THREAD

**Issue by variab1e** [systemjs/plugin-babel#5]
Great work. However I can not for the life of me figure out how to get Stage 1 Features (need decorators) working. I've been trying to import plugins manually in the configuration for most of the day now, and finally had to give up on it. Admittedly I am new to systemjs and babel. Any way you could add Stage 1 or maybe point me in the right direction?

**Comment by guybedford** [comment]
This plugin does not come with stage 1 features as they are unstable and changing.

To add stage one with jspm you can do:

```javascript
jspm install npm:babel-preset-stage-1
```

And then set:

```javascript
System.config({
  babelOptions: {
    presets: ['babel-preset-stage-1']
  }
});
```

**Comment by variab1e** [comment]
Thanks, I'll give that a go. Is there a certain directory that needs to be done from within?

**Comment by guybedford** [comment]
No directory needed just the standard jspm install. If you're not using jspm, I'll see if I can get some docs together for that case as well. I posted https://github.com/systemjs/plugin-babel/issues/6 to track the documentation of this further.

**Comment by variab1e** [comment]
@guybedford Thanks much! I truly appreciate it.
