### ISSUE TITLE
Requiring this file directly for self-executing node.js entrypoint which uses systemjs.

### ISSUE THREAD

**Issue by brainkim** [systemjs/plugin-babel#50]
Hi I was playing around with systemjs and I'm wondering why the following doesn't work.

High-level overview of what I'm trying to do:
I'm trying to execute a `<es6` node file which 1) requires systemjs using commonjs and 2) configures it to recursively build the remainder of my source code with babel by calling `System.import` on a single entry file. I'm running into weird bugs related to promises in node.js and I'd like some help debugging the problem. I don't want to use jspm, switching package managers makes me feel a little crazy, maybe someday, but not today. I just want take advantage of those sweet sweet in-memory builds and bundle arithmetic apis.

I have an executable file called `./manage.js` with the following contents:
```js
#! /usr/bin/env node
var System = require('systemjs');

System.config({
  map: {
    'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
    'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-node.js',
  },
  transpiler: 'plugin-babel',
});

// requiring an es6/es7 file
System.import('./script.js').then((module) => {
  console.log(module());
});

// my trusty stupid catch-all for errors in promises for node.js environments
// executing this file exits silently if I don't include this
process.on('unhandledRejection', function(error, p) {
  console.error(error.stack || error);
  process.exit(1);
}
```
This is in a directory with a `./node_modules` created with an npm install from this `package.json`
```json
{
  "name": "system-js-example",
  "license": "MIT",
  "version": "0.0.0",
  "author": "Brian Kim et al.",
  "scripts": {
    "test": "echo \"hahahaa you fucking goof there are no tests psych 😘 love\""
  },
  "dependencies": {
    "babel": "6.5.2",
    "babel-plugin-transform-runtime": "6.8.0",
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-stage-2": "6.5.0",
    "babel-register": "6.8.0",
    "babel-runtime": "6.6.1",
    "systemjs": "0.19.29",
    "systemjs-plugin-babel": "0.0.11"
  }
}
```
and which tries to `System.import` aka execute the module `./script.js` which looks like
```js
export default async function main() {
  console.log('hi world');
  console.log('uhhh');
}
```
By default, the node process just errors silently. When I add my trusty stupid catch-all for errors in promises for node.js environments, it throws the following error:
```
ReferenceError: /Users/brian/Projects/systemjs-example/script.js: regeneratorIdentifer is not defined
            at Object.runtimeProperty (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:40371:31)
            at PluginPass.exit (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:40569:46)
            at newFn (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:37237:21)
            at NodePath._call (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:33492:20)
            at NodePath.call (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:33464:19)
            at NodePath.visit (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:33526:10)
            at TraversalContext.visitQueue (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:34770:18)
            at TraversalContext.visitMultiple (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:34728:19)
            at TraversalContext.visit (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:34808:21)
            at Function.traverse.node (/Users/brian/Projects/systemjs-example/node_modules/systemjs-plugin-babel/systemjs-babel-node.js:39580:19)
        Error loading /Users/brian/Projects/systemjs-example/script.js
```
If I don't use the async/await stuff, system.js works as I expect it to.

Is this my bad? Have I not found the correct documentation yet for how to set up this use case?

Here's a repository ready-made with the stuff I'm talking about:
https://github.com/brainkim/systemjs-example Just:
```
npm install
./manage.js
```

Thanks!
Brian Kim

**Comment by guybedford** [comment]
I think this was a bug in the last version of `plugin-babel` try updating it to the latest `0.0.12` version?

**Comment by brainkim** [comment]
That solves itI can't figure out how to get systemjs to behave exactly like node/npm, which is preventing me from installing presets/plugins but that's for another issue (probably against systemjs itself).

**Comment by guybedford** [comment]
In the latest SystemJS try `@node/babel-plugin-preset-x` etc.

**Comment by brainkim** [comment]
Hmmmm.... Is this `@node

**Comment by brainkim** [comment]
Hmmmm.... Is this `@node` pragma/directive/whatever it's called new to the latest version?

I can't find any documentation for it. It's working, but I want the files I write to work in both the server and the browser. In other words, if I have a file like so:

```js
import React from `@node/react`;

// bunch of react code
```
Will this work in the browser?

**Comment by guybedford** [comment]
No, which is why this isn't encouraged!

**Comment by brainkim** [comment]
Thanks for all the help!
I was trying really hard to configure SystemJS to use the default node path resolution algorithm in my codebases, but it seems to me that SystemJS might be coupled to jspm in weird ways. I'm looking into jspm right now, but I do wish that SystemJS more easily integrated with npm. It would definitely attract a wider audience which could then transition over to jspm when we get tired of that [goddamn npm spinner](https://github.com/npm/npm/issues/5340). I like the jspm UX so much more, but still, kinda sad that I can't just use npm.

Brian K.i.m.
