### ISSUE TITLE
Decorator plugin doesn't apply to imported dependencies

### ISSUE THREAD

**Issue by tjclement** [systemjs/plugin-babel#52]
For jspm v0.17.22:
When using babel-plugin-transform-decorators-legacy inside of the meta config for *.js, decorators work as expected in a project. Dependencies imported from a project source file, though, throw an error during parsing if they contain decorators (unexpected token on the '@'). The syntax of both decorators is the same.

For example:
```javascript
function decorator(){}

/* Works fine */
@decorator
export class Something {}

/* This file contains decorators as well, and breaks because of Unexpected Token '@' */
import {ArvaRouter} from 'arva-js/routers/ArvaRouter.js';
```

The meta part of jspm.config.js is as follows:

```javascript
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [ "babel-plugin-transform-decorators-legacy" ]
          }
        }
      }
```

The error thrown when an imported dependency uses decorators:

```javascript
     Creating the single-file build for src/main.js...

err  Error on translate for github:bizboard/arva-js@1.0.3/routers/ArvaRouter.js at file:///[..]/ArvaRouter.js
  Loading app/main.js
  SyntaxError: file:///[..]/ArvaRouter.js: Unexpected token (16:0)
  14 | import AnimationController          from 'famous-flex/AnimationController.js';
  15 | 
> 16 | @provide(Router)
     | ^
  17 | export class ArvaRouter extends Router {
  18 | 
  19 |     constructor() {
    at Parser.pp.raise (file:///[..]/systemjs-plugin-babel@0.0.12/systemjs-babel-node.js:29141:15)
```

I created a repro case that shows how decorators work in project source files, but not in imported dependencies, which [can be found here](https://github.com/tjclement/systemjs-dec-repro).

**Comment by guybedford** [comment]
The issue here is that `*.js` actually means `baseURL/*.js` so it does not cover the `github:*` path. The idea here is that these paths are separate configurations.

You can potentially set babelOptions at the baselevel - `System.config({ babelOptions: {...} })` for it to apply to all transpilations. Or alternatively add a `github:*.js` metadata entry.

**Comment by tjclement** [comment]
That was indeed the issue, thanks a lot for your help @guybedford!
