### ISSUE TITLE
Inline sourcemaps not appended to file in node.js environment

### ISSUE THREAD

**Issue by mavericken** [systemjs/plugin-babel#53]
Source maps appears to be working in the browser but not in node.  It looks to me like the transformation simply ignores the sourceMaps: 'inline' option, as the result does seem to have a sourcemaps object, but it was never appended to the output file.

**Comment by mavericken** [comment]
I was able to get it to work with a dirty hack
This: https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L215
To this: 
`
return output.code + '\n//# sourceMappingURL=data:application/json;base64,' + new Buffer(JSON.stringify(output.map)).toString('base64');
`
I assume to get a real non-hack solution to this problem that someone with deeper understanding of this project would need to figure out why the built systemjs-babel-node.js is not tacking on the sourcemap on its own despite sourceMaps: 'inline'.
![image](https://cloud.githubusercontent.com/assets/7833752/16697254/dbc9cdbc-4516-11e6-8edf-d53ff33ccb3d.png)

**Comment by mavericken** [comment]
If someone is kind enough to figure this out, I have provided the example code I used during my investigation:

https://github.com/mavericken/jspm-node-typescript-vscode

**Comment by mavericken** [comment]
Alright, I think I got it actually.  I wrote a pull request for it, but Babel has tons of pull requests, so we may be in for a long wait to get the correct solution.

**Comment by mavericken** [comment]
Nope... I didn't have it.  I personally am ready to settle for the dirty hack I mentioned above, as trying to figure out the right solution is just taking too much time for me.

**Comment by guybedford** [comment]
Thanks for tracking it down - let's follow this feature at the SystemJS issue https://github.com/systemjs/systemjs/issues/1359.
