### ISSUE TITLE
How to specify version of babel?

### ISSUE THREAD

**Issue by ghempton** [systemjs/plugin-babel#60]
I am currently getting hit by a named export hoisting issue using this plugin. I see that it has been fixed here: https://github.com/babel/babel/pull/3594. I am assuming that I am not using the latest version of babel and that is why I am seeing this locally. Is there a way to change the babel version that this plugin uses?

**Comment by guybedford** [comment]
Are you using the latest version of this plugin (0.0.14)?

**Comment by ghempton** [comment]
I am using master directly.

**Comment by guybedford** [comment]
Then you're definitely running the latest version of Babel with that fix. If you can perhaps share a reduced test case that would help to look into it further.

**Comment by ghempton** [comment]
Here is a simple case that causes the issue:

```javascript
export function b(block) {
  return block.trim();
}

export function e(block, element) {
  return `${b(block)}__${element.trim()}`;
}

export function m(element, modifier) {
  return `${element.trim()}--${modifier.trim()}`;
}

export default function bem(block, element, modifier) {
  if (element && modifier) {
    return m(e(block, element), modifier);
  } else if (element) {
    return e(block, element);
  } else if (modifier) {
    return m(b(block), modifier);
  }
  return b(block);
}
```

**Comment by ghempton** [comment]
I think this is due to using an out of date presets package `babel-preset-stage-0`
