### ISSUE TITLE
Please consider including babel-preset-react

### ISSUE THREAD

**Issue by andyearnshaw** [systemjs/plugin-babel#76]
This might also solve some of the other issues with setting up JSX.  I was trying to build locally to see if it added much girth to the resulting files, but I'm having problems 😞.  I'd like this for testing React Components with intern and intern-systemjs-loader, without the precompile-step.  

_systemjs-build-browser.js_ is 733K already, ~50K might not be a noticeable difference (if that is the actual size added).  Alternatively, advice on loading the plugin externally (without adding JSPM as a dependency for intern-systemjs-loader) would be helpful.  At the moment the preset requires too many files, making it difficult to require without setting a *lot* of maps.

**Comment by guybedford** [comment]
@andyearnshaw certainly, and we could put it behind a flag in https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L60 as well.

If you're interested in working on this I'd be happy to explain the process, otherwise will get to it when I can.

**Comment by andyearnshaw** [comment]
@guybedford I managed to get it building, looks like I was just running into https://github.com/jspm/jspm-cli/issues/1030.  When I updated to the beta it built fine.

I'll try and get a PR in soon, thanks 😄.

**Comment by guybedford** [comment]
Thanks, I've released a 0.0.20.
