### ISSUE TITLE
Include stage 2 preset

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-babel#8]
I think it would be safe to make the default preset include Stage 2 as well. This stage represents a comprehensive spec with a complete intention to implement, and only incremental adjustments expected (https://tc39.github.io/process-document/). It makes sense as the cutoff.

**Comment by jmurzy** [comment]
:+1:

**Comment by guybedford** [comment]
Added in https://github.com/systemjs/plugin-babel/commit/b6c5eb0ced0decb8ca2066788c19bb44f3b9f4c3.
