### ISSUE TITLE
toConsumableArray 404

### ISSUE THREAD

**Issue by aendrew** [systemjs/plugin-babel#82]
I use `plugin-babel` in ft-interactive/d3-bootloader and it works fantastic, but whenever I try to splat an object into an array (i.e., `[...objectConst]`), I get the following error:

![toConsumableArray 404](https://user-images.githubusercontent.com/185041/28321908-790b6fc2-6bcc-11e7-9648-044259851ac7.png)

Any idea why?

**Comment by guybedford** [comment]
`babel-helpers` expects to be loaded relative to the path to the babel plugin itself.

This may have something to do with your unpkg config, try configuring it something like:

```js
{
  map: {
    'plugin-babel': 'https://unpkg.com/systemjs-plugin-babel@0.0.25'
  },
  packages: {
    'plugin-babel': {
      main: 'plugin-babel.js'
    }
  }
}
```

**Comment by aendrew** [comment]
Hi @guybedford, thanks for the response. Adding that `packages` stanza to my config totally fixed it! Many thanks! 🙌
